from . import product_template
from . import customer_item_limit
from . import charge_type
from . import commission_agent
from . import commission_line
from . import sale_order
from . import stock_move
from . import account_move
from . import tax_adjustment
